### ISSUE TITLE
How to build X2 in macos 

### ISSUE THREAD

**Issue by Sologala** [lnstadrum/beatmup#17]
@lnstadrum Hi , I want to test shader-style neural network inference with backend of openGL in macos .
When I build this repo. I got following error 

```
[build] Undefined symbols for architecture x86_64:
[build]   "___glewXChooseFBConfig", referenced from:
[build]       Beatmup::GraphicPipeline::Impl::Impl(Beatmup::GraphicPipeline&) in pipeline.cpp.o
[build]   "___glewXCreatePbuffer", referenced from:
[build]       Beatmup::GraphicPipeline::Impl::Impl(Beatmup::GraphicPipeline&) in pipeline.cpp.o
[build]   "___glewXDestroyPbuffer", referenced from:
[build]       Beatmup::GraphicPipeline::~GraphicPipeline() in pipeline.cpp.o
[build]   "___glewXGetVisualFromFBConfig", referenced from:
[build]       Beatmup::GraphicPipeline::Impl::Impl(Beatmup::GraphicPipeline&) in pipeline.cpp.o
[build]   "_glXChooseVisual", referenced from:
[build]       Beatmup::GraphicPipeline::Impl::Impl(Beatmup::GraphicPipeline&) in pipeline.cpp.o
[build]   "_glXCreateContext", referenced from:
[build]       Beatmup::GraphicPipeline::Impl::Impl(Beatmup::GraphicPipeline&) in pipeline.cpp.o
[build]   "_glXDestroyContext", referenced from:
[build]       Beatmup::GraphicPipeline::~GraphicPipeline() in pipeline.cpp.o
[build]       Beatmup::GraphicPipeline::Impl::Impl(Beatmup::GraphicPipeline&) in pipeline.cpp.o
[build]   "_glXMakeCurrent", referenced from:
[build]       Beatmup::GraphicPipeline::Impl::Impl(Beatmup::GraphicPipeline&) in pipeline.cpp.o

```

It seem like that cmake complier did not find glew libs. Although I put following command to cmakeLists.txt ，the error still there.
```
add_subdirectory(glew-cmake)
include_directories(glew-cmake/include)
link_directories(glew-cmake/build/lib)
```

**Comment by lnstadrum** [comment]
Hi @Sologala,

I believe the issue comes from the fact that you compile with GLX backend which might not be available in macOS. I would suggest you to try with plain OpenGL instead. Unfortunately I do not have a mac around to give it a try on my own.

Namely,
 * start from a clean `build` folder to make sure there are no CMake cache files from previous attempts,
 * use the following build command:
```
cmake -DUSE_OPENGL=ON ..
make X2
```

Let me know if this helps.

As for the glew binaries, they are normally already included [here](https://github.com/lnstadrum/beatmup/blob/master/core/CMakeLists.in#L159) in a similar way to what you have tried to do.
