### ISSUE TITLE
fatal error: Python.h: No such file or directory

### ISSUE THREAD

**Issue by BenjaminWegener** [lnstadrum/beatmup#20]
when trying to build beatmup (X2 was built successfully), i receive this error:

`fatal error: Python.h: No such file or directory
`
i then installed libpython3-dev libpython3-all-dev, still the error

**Comment by lnstadrum** [comment]
As discussed in [the related PR](https://github.com/lnstadrum/beatmup/pull/21), the rule of thumb with CMake is **to start from a clean build folder** after any change in case of linker issues (as mentioned in the readme).

`python3-dev` is indeed required to build Python bindings. So after installing it, in order to let to CMake find the newly installed header files, the CMake cache needs to be invalidated (e.g. by starting from a clean build folder).

Thanks @BenjaminWegener for checking this.
