### ISSUE TITLE
Not able to build the code in Windows

### ISSUE THREAD

**Issue by manohargss** [lnstadrum/beatmup#22]
I am getting errors while building the code given in the samples.
![Screenshot 2022-10-14 111214](https://user-images.githubusercontent.com/47656170/195770969-ead031f4-c4f1-40cd-95d0-c6e1f742b8cc.png)

**Comment by lnstadrum** [comment]
Hello,

Thank you for your interest to Beatmup.

Please share more details about your software setup.

Otherwise, GitHub actions performed the windows build of the master branch with success yesterday ([here](https://github.com/lnstadrum/beatmup/actions/runs/3252524795/jobs/5338829137)). You may follow [instructions in the workflow file](https://github.com/lnstadrum/beatmup/actions/runs/3252524795/workflow).

Thank you,
lnstadrum
